spring:
  application:
    name: servicios_api
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  datasource:
    url: jdbc:sqlserver://localhost:58166;databaseName=MS_Servicios;encrypt=true;trustServerCertificate=true;loginTimeout=30;
    username: admincontrabajo
    password: Contrabajo123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

jwt:
  secret: EstaEsUnaClaveSecretaMuyLargaParaQueNadieLaAdivine123456789

app:
  upload:
    fotos-dir: ${user.dir}/uploads/fotos
    max-tamano-bytes: 5242880
    tipos-permitidos: image/jpeg,image/png,image/webp
