spring:
  application:
    name: servicios_api # Este nombre es el "ID" para buscar en Git
  
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  
  cloud:
    config:
      enabled: true
      fail-fast: true # Si el Config Server no responde, la API no arranca (evita errores raros)

# Configuración para ordenar Swagger alfabéticamente
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha